// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using amitranetapi.Helpers;

#nullable disable

namespace amitranetapi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("amitranetapi.Entities.School", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("access_expired_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.Property<string>("affiliation")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<long>("created_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("created_on")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("establish_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("modified_by")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("modified_on")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("organization_id")
                        .HasColumnType("integer");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("photo_path")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("short_name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("id");

                    b.ToTable("School");
                });
#pragma warning restore 612, 618
        }
    }
}
